name: CI Pipeline by DenisLazarian

on:
  push:
    branches: ["develop", "actions/ci-implementation"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: RUXAILAB


    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm ci


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        continue-on-error: true

      - name: Docker build
        run: |
           IMAGE_NAME: ${{ vars.DOCKER_USERNAME }}/$PROJECT_NAME:latest
           docker build -t $IMAGE_NAME .
           docker save $IMAGE_NAME -o $PROJECT_NAME.tar

      - name: Run Test
        run: npm test

        # Para Usar la imagen:
        #   - Extraer del artifact.
        #   - Implementar imagen en máquina local:
  #              docker load -i RUXAILAB.tar # Para cargar la imagen en local
      - name: Upload Docker image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: $PROJECT_MAME.tar





