name: CI Pipeline by DenisLazarian

on:
  push:
    branches: ["develop", "actions/ci-implementation"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm ci
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        continue-on-error: true
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker build
        run: |
          docker build -t RUXAILAB .
          docker save RUXAILAB -o RUXAILAB.tar

      - name: Run Test
        run: npm test
        # Para Usar la imagen:
        #   - Extraer del artifact.
        #   - Implementar imagen en máquina local:
  #              docker load -i RUXAILAB.tar # Para cargar la imagen en local
      - name: Upload Docker image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: RUXAILAB.tar





