name: CI Pipeline by DenisLazarian

on:
  push:
    branches: ["develop"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install axios@1.6.0 && npm ci

      - name: Docker build
        continue-on-error: true
        run: |
          docker build --no-cache -t ruxailab .
          docker save ruxailab -o ruxailab.tar

      - name: Run Test
        run: npm test
        # Para Usar la imagen:
        #   - Extraer del artifact.
        #   - Implementar imagen en máquina local:
  #              docker load -i ruxailab.tar # Para cargar la imagen en local
      - name: Upload Docker image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ruxailab.tar





